A2:
	gcc A_Semaphores.c -o Semaphores
	./Semaphores

A1:
	gcc A_StrictOrdering.c -o StrictOrdering
	./StrictOrdering

B1:
	gcc B_Semaphore.c -o SemaphoresB
	./SemaphoresB

B2:
	gcc B_NoSynchronization.c -o SemaphoresB2
	./SemaphoresB2

clean:
	rm -f ./Semaphores *.o
	rm -f ./StrictOrdering *.o
	rm -f ./SemaphoresB *.o
	rm -f ./SemaphoresB2 *.o