main:
	gcc Shell.c -o Shell
	./Shell

echo:
	gcc echo.c -o echo
	./echo

pwd:
	gcc pwd.c -o pwd
	./pwd

rm:
	gcc rm.c -o rm
	./rm

mkdir:
	gcc mkdir.c -o mkdir
	./mkdir

ls:
	gcc ls.c -o ls
	./ls

date:
	gcc date.c -o date
	./date

cat:
	gcc cat.c -o cat
	./cat